--create table to store roads data with real height
CREATE TABLE IF NOT EXISTS target_ways_{timesign} (
  osm_id               BIGINT,
  ACCESS               TEXT COLLATE pg_catalog."default",
  "addr:housename"     TEXT COLLATE pg_catalog."default",
  "addr:housenumber"   TEXT COLLATE pg_catalog."default",
  "addr:interpolation" TEXT COLLATE pg_catalog."default",
  admin_level          TEXT COLLATE pg_catalog."default",
  aerialway            TEXT COLLATE pg_catalog."default",
  aeroway              TEXT COLLATE pg_catalog."default",
  amenity              TEXT COLLATE pg_catalog."default",
  area                 TEXT COLLATE pg_catalog."default",
  barrier              TEXT COLLATE pg_catalog."default",
  bicycle              TEXT COLLATE pg_catalog."default",
  brand                TEXT COLLATE pg_catalog."default",
  bridge               TEXT COLLATE pg_catalog."default",
  boundary             TEXT COLLATE pg_catalog."default",
  building             TEXT COLLATE pg_catalog."default",
  construction         TEXT COLLATE pg_catalog."default",
  covered              TEXT COLLATE pg_catalog."default",
  culvert              TEXT COLLATE pg_catalog."default",
  cutting              TEXT COLLATE pg_catalog."default",
  denomination         TEXT COLLATE pg_catalog."default",
  disused              TEXT COLLATE pg_catalog."default",
  embankment           TEXT COLLATE pg_catalog."default",
  foot                 TEXT COLLATE pg_catalog."default",
  "generator:source"   TEXT COLLATE pg_catalog."default",
  harbour              TEXT COLLATE pg_catalog."default",
  highway              TEXT COLLATE pg_catalog."default",
  historic             TEXT COLLATE pg_catalog."default",
  horse                TEXT COLLATE pg_catalog."default",
  intermittent         TEXT COLLATE pg_catalog."default",
  junction             TEXT COLLATE pg_catalog."default",
  landuse              TEXT COLLATE pg_catalog."default",
  layer                TEXT COLLATE pg_catalog."default",
  leisure              TEXT COLLATE pg_catalog."default",
  LOCK                 TEXT COLLATE pg_catalog."default",
  man_made             TEXT COLLATE pg_catalog."default",
  military             TEXT COLLATE pg_catalog."default",
  motorcar             TEXT COLLATE pg_catalog."default",
  NAME                 TEXT COLLATE pg_catalog."default",
  "natural"            TEXT COLLATE pg_catalog."default",
  office               TEXT COLLATE pg_catalog."default",
  oneway               TEXT COLLATE pg_catalog."default",
  OPERATOR             TEXT COLLATE pg_catalog."default",
  place                TEXT COLLATE pg_catalog."default",
  population           TEXT COLLATE pg_catalog."default",
  power                TEXT COLLATE pg_catalog."default",
  power_source         TEXT COLLATE pg_catalog."default",
  public_transport     TEXT COLLATE pg_catalog."default",
  railway              TEXT COLLATE pg_catalog."default",
  REF                  TEXT COLLATE pg_catalog."default",
  religion             TEXT COLLATE pg_catalog."default",
  route                TEXT COLLATE pg_catalog."default",
  service              TEXT COLLATE pg_catalog."default",
  shop                 TEXT COLLATE pg_catalog."default",
  sport                TEXT COLLATE pg_catalog."default",
  surface              TEXT COLLATE pg_catalog."default",
  toll                 TEXT COLLATE pg_catalog."default",
  tourism              TEXT COLLATE pg_catalog."default",
  "tower:type"         TEXT COLLATE pg_catalog."default",
  tracktype            TEXT COLLATE pg_catalog."default",
  tunnel               TEXT COLLATE pg_catalog."default",
  water                TEXT COLLATE pg_catalog."default",
  waterway             TEXT COLLATE pg_catalog."default",
  wetland              TEXT COLLATE pg_catalog."default",
  width                TEXT COLLATE pg_catalog."default",
  wood                 TEXT COLLATE pg_catalog."default",
  z_order              INTEGER,
  road_code_list       TEXT COLLATE pg_catalog."default",
  way_area             REAL,
  way                  GEOMETRY
);